namespace FieldsAndPropertise
{
    internal class Program
    {
        static void Main1()
        {
            Class2  o;
            o = new Class2();

            o.seti(1000);
            Console.WriteLine(o.geti());

        }

        static void Main()
        {
            Class1 o = new Class1();

            o.I = 10;  //set
            Console.WriteLine(o.I);  //get

            o.P3 = 20;
            Console.WriteLine(o.P3);

        }
    }


    public class Class2
    {
        private int i;  //field
        public void seti(int VALUE)
        {
            if (VALUE <= 100)
                i = VALUE;
            else
                Console.WriteLine("Invalied value for i");
        }
        public int geti()
        {
            return i;
        }
    }

    public class Class1
    {
        private int i;
        public int I
        {
            set
            {
                if (value <= 100)
                    i = value;
                else
                    Console.WriteLine("Invalid value for i");
            }
            get
            {
                return i;
            }
        }

        private string p1;
        public string P1
        {
            set
            {
                p1 = value;
            }
            get
            {
                return p1;
            }
        }
        public string P2;




        //automatic property -  when there are no validations
        //get and set is auto generated by the compiler
        //private variable is auto generated by the compiler

        public int P3 { get; set; }


    }

    
}